schedule_interval: "30 * * * *"
tables:
    - click
    - imp
    - info
    - spot
    - state
    - track
    - int
stage_sql_path: adlogs/load_raw_logs
transform_sql_path: adlogs/transform_log
parent_directory: 'stage_{}_logs_dev'
log_path: 'log/*'
