schedule_interval: "30 * * * *"
tables:
    click:
      - ipn_blacklist
      - smart_clip_patch
    imp:
      - ipn_blacklist
      - smart_clip_patch
    state:
      - ipn_blacklist
    int:
      - set_interaction_smartclip_placement
processes:
    - ipn_blacklist
stage_sql_path: adlogs/load_raw_logs
transform_sql_path: adlogs/transform_logs
# second dag sql path
transform_log_path: adlogs/log_process
parent_directory: 'stage_{}_logs_dev'
log_path: 'log/*'
